sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedabdelmaguid/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true ahmedabdelmaguid/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-401515762196"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

